// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxmpwqvgoxvpcdsdulfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bXB3cXZnb3h2cGNkc2R1bGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDUwNDIsImV4cCI6MjA2NTI4MTA0Mn0._J7YFVR5TWFzoCRfPMXVGgUNEQt_yhpUqV0yMxeQ8oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);